// Generated by gencpp from file amazing_car/my_angle_msg.msg
// DO NOT EDIT!


#ifndef AMAZING_CAR_MESSAGE_MY_ANGLE_MSG_H
#define AMAZING_CAR_MESSAGE_MY_ANGLE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace amazing_car
{
template <class ContainerAllocator>
struct my_angle_msg_
{
  typedef my_angle_msg_<ContainerAllocator> Type;

  my_angle_msg_()
    : yaw(0.0)  {
    }
  my_angle_msg_(const ContainerAllocator& _alloc)
    : yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::amazing_car::my_angle_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amazing_car::my_angle_msg_<ContainerAllocator> const> ConstPtr;

}; // struct my_angle_msg_

typedef ::amazing_car::my_angle_msg_<std::allocator<void> > my_angle_msg;

typedef boost::shared_ptr< ::amazing_car::my_angle_msg > my_angle_msgPtr;
typedef boost::shared_ptr< ::amazing_car::my_angle_msg const> my_angle_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amazing_car::my_angle_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amazing_car::my_angle_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace amazing_car

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'amazing_car': ['/home/jlurobot/catkin_ws/src/amazing_car/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::amazing_car::my_angle_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amazing_car::my_angle_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amazing_car::my_angle_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amazing_car::my_angle_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amazing_car::my_angle_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amazing_car::my_angle_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amazing_car::my_angle_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2160bf7632f25ad6dc7c5aab561198d4";
  }

  static const char* value(const ::amazing_car::my_angle_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2160bf7632f25ad6ULL;
  static const uint64_t static_value2 = 0xdc7c5aab561198d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::amazing_car::my_angle_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amazing_car/my_angle_msg";
  }

  static const char* value(const ::amazing_car::my_angle_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amazing_car::my_angle_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 yaw\n\
";
  }

  static const char* value(const ::amazing_car::my_angle_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amazing_car::my_angle_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_angle_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amazing_car::my_angle_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amazing_car::my_angle_msg_<ContainerAllocator>& v)
  {
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMAZING_CAR_MESSAGE_MY_ANGLE_MSG_H
