// Generated by gencpp from file amazing_car/my_gps_state.msg
// DO NOT EDIT!


#ifndef AMAZING_CAR_MESSAGE_MY_GPS_STATE_H
#define AMAZING_CAR_MESSAGE_MY_GPS_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace amazing_car
{
template <class ContainerAllocator>
struct my_gps_state_
{
  typedef my_gps_state_<ContainerAllocator> Type;

  my_gps_state_()
    : location_state(0)
    , angle_state(0)  {
    }
  my_gps_state_(const ContainerAllocator& _alloc)
    : location_state(0)
    , angle_state(0)  {
  (void)_alloc;
    }



   typedef int32_t _location_state_type;
  _location_state_type location_state;

   typedef int32_t _angle_state_type;
  _angle_state_type angle_state;





  typedef boost::shared_ptr< ::amazing_car::my_gps_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amazing_car::my_gps_state_<ContainerAllocator> const> ConstPtr;

}; // struct my_gps_state_

typedef ::amazing_car::my_gps_state_<std::allocator<void> > my_gps_state;

typedef boost::shared_ptr< ::amazing_car::my_gps_state > my_gps_statePtr;
typedef boost::shared_ptr< ::amazing_car::my_gps_state const> my_gps_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amazing_car::my_gps_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amazing_car::my_gps_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace amazing_car

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'amazing_car': ['/home/jlurobot/catkin_ws/src/amazing_car/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::amazing_car::my_gps_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amazing_car::my_gps_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amazing_car::my_gps_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amazing_car::my_gps_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amazing_car::my_gps_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amazing_car::my_gps_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amazing_car::my_gps_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c597a44bb73f53d7407fbd84dfc626db";
  }

  static const char* value(const ::amazing_car::my_gps_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc597a44bb73f53d7ULL;
  static const uint64_t static_value2 = 0x407fbd84dfc626dbULL;
};

template<class ContainerAllocator>
struct DataType< ::amazing_car::my_gps_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amazing_car/my_gps_state";
  }

  static const char* value(const ::amazing_car::my_gps_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amazing_car::my_gps_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 location_state\n\
int32 angle_state\n\
";
  }

  static const char* value(const ::amazing_car::my_gps_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amazing_car::my_gps_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location_state);
      stream.next(m.angle_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_gps_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amazing_car::my_gps_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amazing_car::my_gps_state_<ContainerAllocator>& v)
  {
    s << indent << "location_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.location_state);
    s << indent << "angle_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.angle_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMAZING_CAR_MESSAGE_MY_GPS_STATE_H
